# Generated by Django 6.0 on 2025-12-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('ordem_exibicao', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_produto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('qr_code_slug', models.CharField(max_length=120, unique=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('fuso_horario', models.CharField(max_length=40)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurante',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=12)),
                ('total_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aberta_em', models.DateTimeField(blank=True, null=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.cliente')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante')),
            ],
            options={
                'db_table': 'comanda',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('preparado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.comanda')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.mesa')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem_exibicao', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.categoriaproduto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome_produto_snapshot', models.CharField(max_length=100)),
                ('preco_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.produto')),
            ],
            options={
                'db_table': 'item_pedido',
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante'),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('ultimo_login_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.restaurante')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PedidoStatusHistorico',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.pedido')),
                ('alterado_por', models.ForeignKey(blank=True, db_column='alterado_por', null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.usuario')),
            ],
            options={
                'db_table': 'pedido_status_historico',
            },
        ),
        migrations.AddField(
            model_name='comanda',
            name='encerrada_por',
            field=models.ForeignKey(blank=True, db_column='encerrada_por', null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('restaurante', 'cpf')},
        ),
    ]
