# Generated by Django 6.0 on 2025-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='eh_popular',
            field=models.BooleanField(default=False, verbose_name='É Queridinho?'),
        ),
    ]
