# Generated by Django 6.0 on 2026-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_pedido_tipo_entrega_alter_pedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='qr_code_slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
